[test]
# Test configuration for Bun
preload = ["./src/test/setup.ts"]
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { line = 80 }

# Timeout for tests (5 seconds)
timeout = 5000

# Run tests in parallel
concurrent = true